imports:
    - { resource: config_test.yml }

framework:
    profiler:
        only_exceptions: false
        collect: true

web_profiler:
    toolbar: true

eight_points_guzzle:
    logging: true
    clients:
        local_test_api:
            base_url: http://127.0.0.1:8000/app_dev.php/

# Oneup Flysystem
oneup_flysystem:
    adapters:
        local_adapter:
            local:
                directory: %kernel.root_dir%/../features/uploadTemp


